### ISSUE TITLE
collections vs collections.abc deprecation issue in bitbake

### ISSUE THREAD

**Issue by SMotlaq** [sadeghimoghaddam/licheepi_sdk#1]
I'm following a tutorial video on your [YouTube channel](https://www.youtube.com/@mohsensadeghimoghaddam8784/videos), but I encountered an issue related to the collections vs collections.abc deprecation. I've attached an image of the error I'm seeing: 

![image](https://github.com/user-attachments/assets/910f2024-207f-48e0-8c12-8c182731a7b8)

After researching online, I found that this issue was fixed in bitbake via [this commit](https://git.openembedded.org/bitbake/commit/?h=1.46&id=4b66d498eab22eca29c9e3a7fdfa5c6e54055e78). As a newcomer to embedded Linux, I'm a bit confused and would appreciate your help in resolving this issue. I'm new to embedded Linux and would appreciate any guidance on how to resolve this issue.

**Comment by sadeghimoghaddam** [comment]
As far as I know in newer versions of Python, MutableMapping has been moved from the collections module to collections.abc. To fix this, you can update your code from:
          from collections import MutableMapping
to : 
         from collections.abc import MutableMapping

I hope that just changing this file will solve the issue and that there won’t be any other dependencies. Generally, the problem comes from the Python version, which has always caused issues for me! If the problem isn’t resolved, please download the latest version of Yocto and only add the LitcheePi layer to it, and perform the build with that. In other words, don’t use this SDK to avoid problems with the Python version. This SDK is using an older version.
